name: do this on workflow run

on:
  workflow_run:
    workflows: ["GitHub Actions Demo"]
    types:
      - completed
jobs:
  do_stuff:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
